name: Ping Website Every 12 Minutes

on:
  schedule:
    - cron: "*/12 * * * *"  # Every 12 minutes
  workflow_dispatch:       # Allow manual runs too

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping website
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://nougat-eight.vercel.app/
