name: Ping Website Every 5 Minutes From 1 AM to 11 PM

on:
  schedule:
    - cron: '0 1-23 * * *'   # minute 0 past each hour
    - cron: '5 1-23 * * *'   # minute 5 past each hour
    - cron: '10 1-23 * * *'
    - cron: '15 1-23 * * *'
    - cron: '20 1-23 * * *'
    - cron: '25 1-23 * * *'
    - cron: '30 1-23 * * *'
    - cron: '35 1-23 * * *'
    - cron: '40 1-23 * * *'
    - cron: '45 1-23 * * *'
    - cron: '50 1-23 * * *'
    - cron: '55 1-23 * * *'
  workflow_dispatch:         # Allow manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping /articles page
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://nougat-f609.onrender.com/api/articles
